# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='local_img',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
