# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180704_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='jyg0172@naver.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='guide_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='local_img/logo2.png', upload_to='user_img'),
        ),
        migrations.AddField(
            model_name='post',
            name='next_country',
            field=models.CharField(default='ch', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.CharField(max_length=60),
        ),
    ]
